# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cards.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cards.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63\x61rds.proto\"\x1e\n\x0b\x43\x61rdRequest\x12\x0f\n\x07\x63\x61rd_id\x18\x01 \x01(\x05\"\x9a\x01\n\x0c\x43\x61rdResponse\x12\x0f\n\x07\x63\x61rd_id\x18\x01 \x01(\x05\x12\x11\n\tcard_name\x18\x02 \x01(\t\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x13\n\x0bpercentages\x18\x05 \x01(\x01\x12\x13\n\x0bpicture_url\x18\x06 \x01(\t\x12\r\n\x05likes\x18\x07 \x01(\x05\x12\x10\n\x08\x64islikes\x18\x08 \x01(\x05\"6\n\x12ReactOnCardRequest\x12\x0f\n\x07\x63\x61rd_id\x18\x01 \x01(\x05\x12\x0f\n\x07is_like\x18\x02 \x01(\x08\x32\x62\n\x05\x43\x61rds\x12&\n\x07GetCard\x12\x0c.CardRequest\x1a\r.CardResponse\x12\x31\n\x0bReactOnCard\x12\x13.ReactOnCardRequest\x1a\r.CardResponseb\x06proto3'
)




_CARDREQUEST = _descriptor.Descriptor(
  name='CardRequest',
  full_name='CardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_id', full_name='CardRequest.card_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=45,
)


_CARDRESPONSE = _descriptor.Descriptor(
  name='CardResponse',
  full_name='CardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_id', full_name='CardResponse.card_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='card_name', full_name='CardResponse.card_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brand', full_name='CardResponse.brand', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='CardResponse.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentages', full_name='CardResponse.percentages', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='picture_url', full_name='CardResponse.picture_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='likes', full_name='CardResponse.likes', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dislikes', full_name='CardResponse.dislikes', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=202,
)


_REACTONCARDREQUEST = _descriptor.Descriptor(
  name='ReactOnCardRequest',
  full_name='ReactOnCardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_id', full_name='ReactOnCardRequest.card_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_like', full_name='ReactOnCardRequest.is_like', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=258,
)

DESCRIPTOR.message_types_by_name['CardRequest'] = _CARDREQUEST
DESCRIPTOR.message_types_by_name['CardResponse'] = _CARDRESPONSE
DESCRIPTOR.message_types_by_name['ReactOnCardRequest'] = _REACTONCARDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CardRequest = _reflection.GeneratedProtocolMessageType('CardRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARDREQUEST,
  '__module__' : 'cards_pb2'
  # @@protoc_insertion_point(class_scope:CardRequest)
  })
_sym_db.RegisterMessage(CardRequest)

CardResponse = _reflection.GeneratedProtocolMessageType('CardResponse', (_message.Message,), {
  'DESCRIPTOR' : _CARDRESPONSE,
  '__module__' : 'cards_pb2'
  # @@protoc_insertion_point(class_scope:CardResponse)
  })
_sym_db.RegisterMessage(CardResponse)

ReactOnCardRequest = _reflection.GeneratedProtocolMessageType('ReactOnCardRequest', (_message.Message,), {
  'DESCRIPTOR' : _REACTONCARDREQUEST,
  '__module__' : 'cards_pb2'
  # @@protoc_insertion_point(class_scope:ReactOnCardRequest)
  })
_sym_db.RegisterMessage(ReactOnCardRequest)



_CARDS = _descriptor.ServiceDescriptor(
  name='Cards',
  full_name='Cards',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=260,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCard',
    full_name='Cards.GetCard',
    index=0,
    containing_service=None,
    input_type=_CARDREQUEST,
    output_type=_CARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReactOnCard',
    full_name='Cards.ReactOnCard',
    index=1,
    containing_service=None,
    input_type=_REACTONCARDREQUEST,
    output_type=_CARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARDS)

DESCRIPTOR.services_by_name['Cards'] = _CARDS

# @@protoc_insertion_point(module_scope)
