/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.3
// source: protobufs/cards.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./cards_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.CardsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.CardsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CardRequest,
 *   !proto.CardResponse>}
 */
const methodDescriptor_Cards_GetCard = new grpc.web.MethodDescriptor(
  '/Cards/GetCard',
  grpc.web.MethodType.UNARY,
  proto.CardRequest,
  proto.CardResponse,
  /**
   * @param {!proto.CardRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CardResponse.deserializeBinary
);


/**
 * @param {!proto.CardRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CardResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CardResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CardsClient.prototype.getCard =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Cards/GetCard',
      request,
      metadata || {},
      methodDescriptor_Cards_GetCard,
      callback);
};


/**
 * @param {!proto.CardRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CardResponse>}
 *     Promise that resolves to the response
 */
proto.CardsPromiseClient.prototype.getCard =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Cards/GetCard',
      request,
      metadata || {},
      methodDescriptor_Cards_GetCard);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ReactOnCardRequest,
 *   !proto.CardResponse>}
 */
const methodDescriptor_Cards_ReactOnCard = new grpc.web.MethodDescriptor(
  '/Cards/ReactOnCard',
  grpc.web.MethodType.UNARY,
  proto.ReactOnCardRequest,
  proto.CardResponse,
  /**
   * @param {!proto.ReactOnCardRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CardResponse.deserializeBinary
);


/**
 * @param {!proto.ReactOnCardRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CardResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CardResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CardsClient.prototype.reactOnCard =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Cards/ReactOnCard',
      request,
      metadata || {},
      methodDescriptor_Cards_ReactOnCard,
      callback);
};


/**
 * @param {!proto.ReactOnCardRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CardResponse>}
 *     Promise that resolves to the response
 */
proto.CardsPromiseClient.prototype.reactOnCard =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Cards/ReactOnCard',
      request,
      metadata || {},
      methodDescriptor_Cards_ReactOnCard);
};


module.exports = proto;

