version: '3.1'

services:
  clickhouse:
    image: bitnami/clickhouse:latest
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=pass
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - ./data/clickhouse:/bitnami/clickhouse
        - ./db/clickhouse/:/docker-entrypoint-initdb.d/
        - ./db:/csv/
  relational:
      image: mariadb:10.9.4
      environment:
        MYSQL_ROOT_PASSWORD: pass
      expose: 
        - 3306
      ports:
        - '3306:3306'
      volumes:
      - ./data/relational:/var/lib/mysql
      - ./db/mariadb:/docker-entrypoint-initdb.d/
      - ./db:/csv/